pipeline:
  identifier: Build_shreelola1_buildbuddy_1706584841038
  name: Build buildbuddy
  orgIdentifier: default
  projectIdentifier: test12
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1706149286937
        repoName: shreelola1/buildbuddy
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: gobuild
                  name: go_build
                  spec:
                    command: go build
                  timeout: ""
                  type: Run
              - step:
                  identifier: gotest
                  name: go_test
                  spec:
                    command: go test -v ./...
                  timeout: ""
                  type: Run
              - step:
                  identifier: npminstall
                  name: npm_install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
